var searchData=
[
  ['handler_0',['handler',['../structdmlc_1_1serializer_1_1Handler.html',1,'dmlc::serializer::Handler&lt; T &gt;'],['../structdmlc_1_1lua__stack_1_1Handler.html',1,'dmlc::lua_stack::Handler&lt; T &gt;']]],
  ['handler_3c_20xgboost_3a_3aentry_20_3e_1',['Handler&lt; xgboost::Entry &gt;',['../structdmlc_1_1serializer_1_1Handler_3_01xgboost_1_1Entry_01_4.html',1,'dmlc::serializer']]],
  ['handleseprecord_2',['handleSepRecord',['../structhandleSepRecord.html',1,'']]],
  ['handleseprecord_3c_20tuple_2c_200_20_3e_3',['handleSepRecord&lt; Tuple, 0 &gt;',['../structhandleSepRecord_3_01Tuple_00_010_01_4.html',1,'']]],
  ['handlesinglepos_4',['handleSinglePos',['../structhandleSinglePos.html',1,'']]],
  ['has_5ffrom_5fjson_5',['has_from_json',['../structdetail_1_1has__from__json.html',1,'detail']]],
  ['has_5ffrom_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_6',['has_from_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html',1,'detail']]],
  ['has_5fkey_5fcompare_7',['has_key_compare',['../structdetail_1_1has__key__compare.html',1,'detail']]],
  ['has_5fnon_5fdefault_5ffrom_5fjson_8',['has_non_default_from_json',['../structdetail_1_1has__non__default__from__json.html',1,'detail']]],
  ['has_5fnon_5fdefault_5ffrom_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_9',['has_non_default_from_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_912047717fa07cfa9d99fe9eafcf1e11e.html',1,'detail']]],
  ['has_5fsaveload_10',['has_saveload',['../structdmlc_1_1has__saveload.html',1,'dmlc']]],
  ['has_5fto_5fjson_11',['has_to_json',['../structdetail_1_1has__to__json.html',1,'detail']]],
  ['has_5fto_5fjson_3c_20basicjsontype_2c_20t_2c_20enable_5fif_5ft_3c_20_21is_5fbasic_5fjson_3c_20t_20_3e_3a_3avalue_20_3e_20_3e_12',['has_to_json&lt; BasicJsonType, T, enable_if_t&lt; !is_basic_json&lt; T &gt;::value &gt; &gt;',['../structdetail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html',1,'detail']]],
  ['hasarbitraryparamsdict_13',['HasArbitraryParamsDict',['../classxgboost_1_1spark_1_1params_1_1HasArbitraryParamsDict.html',1,'xgboost::spark::params']]],
  ['hasbasemargincol_14',['HasBaseMarginCol',['../classxgboost_1_1spark_1_1params_1_1HasBaseMarginCol.html',1,'xgboost::spark::params']]],
  ['hascontribpredictioncol_15',['HasContribPredictionCol',['../classxgboost_1_1spark_1_1params_1_1HasContribPredictionCol.html',1,'xgboost::spark::params']]],
  ['hasenablesparsedataoptim_16',['HasEnableSparseDataOptim',['../classxgboost_1_1spark_1_1params_1_1HasEnableSparseDataOptim.html',1,'xgboost::spark::params']]],
  ['hasfeaturescols_17',['HasFeaturesCols',['../classxgboost_1_1spark_1_1params_1_1HasFeaturesCols.html',1,'xgboost::spark::params']]],
  ['hash_18',['hash',['../structxgboost_1_1DMatrixCache_1_1Hash.html',1,'xgboost::DMatrixCache&lt; CacheT &gt;::Hash'],['../structxgboost_1_1IntrusivePtr_1_1Hash.html',1,'xgboost::IntrusivePtr&lt; T &gt;::Hash']]],
  ['hash_3c_20nlohmann_3a_3anlohmann_5fbasic_5fjson_5ftpl_20_3e_19',['hash&lt; nlohmann::NLOHMANN_BASIC_JSON_TPL &gt;',['../structstd_1_1hash_3_01nlohmann_1_1NLOHMANN__BASIC__JSON__TPL_01_4.html',1,'std']]],
  ['hash_3c_20xgboost_3a_3aintrusiveptr_3c_20t_20_3e_20_3e_20',['hash&lt; xgboost::IntrusivePtr&lt; T &gt; &gt;',['../structstd_1_1hash_3_01xgboost_1_1IntrusivePtr_3_01T_01_4_01_4.html',1,'std']]],
  ['hashfunction_21',['hashfunction',['../structEffected__Field_1_1HashFunction.html',1,'Effected_Field::HashFunction'],['../structjson__req__export_1_1HashFunction.html',1,'json_req_export::HashFunction']]],
  ['hasqueryidcol_22',['HasQueryIdCol',['../classxgboost_1_1spark_1_1params_1_1HasQueryIdCol.html',1,'xgboost::spark::params']]],
  ['hdfsfilesystem_23',['HDFSFileSystem',['../classdmlc_1_1io_1_1HDFSFileSystem.html',1,'dmlc::io']]],
  ['hdfsstream_24',['HDFSStream',['../classdmlc_1_1io_1_1HDFSStream.html',1,'dmlc::io']]],
  ['heap_5felem_25',['heap_elem',['../structheap__elem.html',1,'']]],
  ['histcollection_26',['HistCollection',['../classxgboost_1_1common_1_1HistCollection.html',1,'xgboost::common']]],
  ['histevaluator_27',['HistEvaluator',['../classxgboost_1_1tree_1_1HistEvaluator.html',1,'xgboost::tree']]],
  ['histmakertrainparam_28',['HistMakerTrainParam',['../structxgboost_1_1tree_1_1HistMakerTrainParam.html',1,'xgboost::tree']]],
  ['histmultievaluator_29',['HistMultiEvaluator',['../classxgboost_1_1tree_1_1HistMultiEvaluator.html',1,'xgboost::tree']]],
  ['histogrambinentry_30',['HistogramBinEntry',['../structLightGBM_1_1HistogramBinEntry.html',1,'LightGBM']]],
  ['histogrambuilder_31',['HistogramBuilder',['../classxgboost_1_1tree_1_1HistogramBuilder.html',1,'xgboost::tree']]],
  ['histogramcuts_32',['HistogramCuts',['../classxgboost_1_1common_1_1HistogramCuts.html',1,'xgboost::common']]],
  ['histogrampool_33',['HistogramPool',['../classLightGBM_1_1HistogramPool.html',1,'LightGBM']]],
  ['histupdater_34',['HistUpdater',['../classxgboost_1_1tree_1_1HistUpdater.html',1,'xgboost::tree']]],
  ['hostdevicevector_35',['HostDeviceVector',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5ffloat_20_3e_36',['HostDeviceVector&lt; bst_float &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5fgroup_5ft_20_3e_37',['HostDeviceVector&lt; bst_group_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20bst_5frow_5ft_20_3e_38',['HostDeviceVector&lt; bst_row_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20double_20_3e_39',['HostDeviceVector&lt; double &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20featuretype_20_3e_40',['HostDeviceVector&lt; FeatureType &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20float_20_3e_41',['HostDeviceVector&lt; float &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20int_20_3e_42',['HostDeviceVector&lt; int &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20int32_5ft_20_3e_43',['HostDeviceVector&lt; int32_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20std_3a_3asize_5ft_20_3e_44',['HostDeviceVector&lt; std::size_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20std_3a_3auint8_5ft_20_3e_45',['HostDeviceVector&lt; std::uint8_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20uint32_5ft_20_3e_46',['HostDeviceVector&lt; uint32_t &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20xgboost_3a_3adetail_3a_3agradientpairinternal_20_3e_47',['HostDeviceVector&lt; xgboost::detail::GradientPairInternal &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevector_3c_20xgboost_3a_3aentry_20_3e_48',['HostDeviceVector&lt; xgboost::Entry &gt;',['../classxgboost_1_1HostDeviceVector.html',1,'xgboost']]],
  ['hostdevicevectorimpl_49',['HostDeviceVectorImpl',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5ffloat_20_3e_50',['HostDeviceVectorImpl&lt; bst_float &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5fgroup_5ft_20_3e_51',['HostDeviceVectorImpl&lt; bst_group_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20bst_5frow_5ft_20_3e_52',['HostDeviceVectorImpl&lt; bst_row_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20double_20_3e_53',['HostDeviceVectorImpl&lt; double &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20featuretype_20_3e_54',['HostDeviceVectorImpl&lt; FeatureType &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20float_20_3e_55',['HostDeviceVectorImpl&lt; float &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20int_20_3e_56',['HostDeviceVectorImpl&lt; int &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20int32_5ft_20_3e_57',['HostDeviceVectorImpl&lt; int32_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20std_3a_3asize_5ft_20_3e_58',['HostDeviceVectorImpl&lt; std::size_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20std_3a_3auint8_5ft_20_3e_59',['HostDeviceVectorImpl&lt; std::uint8_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20uint32_5ft_20_3e_60',['HostDeviceVectorImpl&lt; uint32_t &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20xgboost_3a_3adetail_3a_3agradientpairinternal_20_3e_61',['HostDeviceVectorImpl&lt; xgboost::detail::GradientPairInternal &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostdevicevectorimpl_3c_20xgboost_3a_3aentry_20_3e_62',['HostDeviceVectorImpl&lt; xgboost::Entry &gt;',['../structxgboost_1_1HostDeviceVectorImpl.html',1,'xgboost']]],
  ['hostsketchcontainer_63',['HostSketchContainer',['../classxgboost_1_1common_1_1HostSketchContainer.html',1,'xgboost::common']]],
  ['hostsparsepageview_64',['HostSparsePageView',['../structxgboost_1_1HostSparsePageView.html',1,'xgboost']]],
  ['httpreadstream_65',['HttpReadStream',['../classdmlc_1_1io_1_1s3_1_1HttpReadStream.html',1,'dmlc::io::s3']]],
  ['huberlossmetric_66',['HuberLossMetric',['../classLightGBM_1_1HuberLossMetric.html',1,'LightGBM']]]
];
