var searchData=
[
  ['bart_0',['BART',['../classBART.html',1,'']]],
  ['bart_5fnode_1',['bart_node',['../classbart__node.html',1,'']]],
  ['bart_5fparams_2',['bart_params',['../classbart__params.html',1,'']]],
  ['bart_5ftree_3',['bart_tree',['../classbart__tree.html',1,'']]],
  ['base64instream_4',['Base64InStream',['../classxgboost_1_1common_1_1Base64InStream.html',1,'xgboost::common']]],
  ['base64outstream_5',['Base64OutStream',['../classxgboost_1_1common_1_1Base64OutStream.html',1,'xgboost::common']]],
  ['baseclass_6',['BaseClass',['../structxgboost_1_1common_1_1BaseClass.html',1,'xgboost::common']]],
  ['basefederatedtest_7',['BaseFederatedTest',['../classxgboost_1_1BaseFederatedTest.html',1,'xgboost']]],
  ['baselogger_8',['BaseLogger',['../classxgboost_1_1BaseLogger.html',1,'xgboost']]],
  ['basemgputest_9',['BaseMGPUTest',['../classxgboost_1_1BaseMGPUTest.html',1,'xgboost']]],
  ['basicfeatgenerator_10',['BasicFeatGenerator',['../classBasicFeatGenerator.html',1,'']]],
  ['basicfilteringparams_11',['BasicFilteringParams',['../structBasicFilteringParams.html',1,'']]],
  ['basicrowiter_12',['BasicRowIter',['../classdmlc_1_1data_1_1BasicRowIter.html',1,'dmlc::data']]],
  ['basicsamplefilter_13',['BasicSampleFilter',['../classBasicSampleFilter.html',1,'']]],
  ['basictestfilter_14',['BasicTestFilter',['../classBasicTestFilter.html',1,'']]],
  ['basictrainfilter_15',['BasicTrainFilter',['../classBasicTrainFilter.html',1,'']]],
  ['basicwalkthrough_16',['BasicWalkThrough',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1BasicWalkThrough.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['batchiterator_17',['BatchIterator',['../classxgboost_1_1BatchIterator.html',1,'xgboost']]],
  ['batchiteratorimpl_18',['BatchIteratorImpl',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20cscpage_20_3e_19',['BatchIteratorImpl&lt; CSCPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20ellpackpage_20_3e_20',['BatchIteratorImpl&lt; EllpackPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20ghistindexmatrix_20_3e_21',['BatchIteratorImpl&lt; GHistIndexMatrix &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20s_20_3e_22',['BatchIteratorImpl&lt; S &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20sortedcscpage_20_3e_23',['BatchIteratorImpl&lt; SortedCSCPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20sparsepage_20_3e_24',['BatchIteratorImpl&lt; SparsePage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchparam_25',['BatchParam',['../structxgboost_1_1BatchParam.html',1,'xgboost']]],
  ['batchset_26',['BatchSet',['../classxgboost_1_1BatchSet.html',1,'xgboost']]],
  ['bigdensematrix_27',['BigDenseMatrix',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1util_1_1BigDenseMatrix.html',1,'ml::dmlc::xgboost4j::java::util']]],
  ['bin_28',['Bin',['../classLightGBM_1_1Bin.html',1,'LightGBM']]],
  ['binaryerrormetric_29',['BinaryErrorMetric',['../classLightGBM_1_1BinaryErrorMetric.html',1,'LightGBM']]],
  ['binarylogloss_30',['BinaryLogloss',['../classLightGBM_1_1BinaryLogloss.html',1,'LightGBM']]],
  ['binaryloglossmetric_31',['BinaryLoglossMetric',['../classLightGBM_1_1BinaryLoglossMetric.html',1,'LightGBM']]],
  ['binarymetric_32',['BinaryMetric',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarymetric_3c_20binaryerrormetric_20_3e_33',['BinaryMetric&lt; BinaryErrorMetric &gt;',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarymetric_3c_20binaryloglossmetric_20_3e_34',['BinaryMetric&lt; BinaryLoglossMetric &gt;',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarytree_35',['BinaryTree',['../structtree_1_1BinaryTree.html',1,'tree']]],
  ['biniterator_36',['BinIterator',['../classLightGBM_1_1BinIterator.html',1,'LightGBM']]],
  ['binmapper_37',['BinMapper',['../classLightGBM_1_1BinMapper.html',1,'LightGBM']]],
  ['binnedlmestimates_38',['BinnedLmEstimates',['../classBinnedLmEstimates.html',1,'']]],
  ['binnedlmestimatesparams_39',['BinnedLmEstimatesParams',['../structBinnedLmEstimatesParams.html',1,'']]],
  ['binning_5fwrapper_40',['Binning_Wrapper',['../classBinning__Wrapper.html',1,'']]],
  ['binningfeatprocessor_41',['BinningFeatProcessor',['../classBinningFeatProcessor.html',1,'']]],
  ['binsettings_42',['BinSettings',['../classBinSettings.html',1,'']]],
  ['binsplitoptimizer_43',['BinSplitOptimizer',['../classBinSplitOptimizer.html',1,'']]],
  ['bitand_44',['BitAND',['../structrabit_1_1op_1_1BitAND.html',1,'rabit::op']]],
  ['bitfieldcontainer_45',['BitFieldContainer',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20uint32_5ft_2c_20lbitspolicy_3c_20uint32_5ft_20_3e_20_3e_46',['BitFieldContainer&lt; uint32_t, LBitsPolicy&lt; uint32_t &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20uint8_5ft_2c_20rbitspolicy_3c_20unsigned_20char_20_3e_20_3e_47',['BitFieldContainer&lt; uint8_t, RBitsPolicy&lt; unsigned char &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20vt_2c_20lbitspolicy_3c_20vt_2c_20false_20_3e_2c_20false_20_3e_48',['BitFieldContainer&lt; VT, LBitsPolicy&lt; VT, false &gt;, false &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20vt_2c_20rbitspolicy_3c_20vt_20_3e_20_3e_49',['BitFieldContainer&lt; VT, RBitsPolicy&lt; VT &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitor_50',['BitOR',['../structrabit_1_1op_1_1BitOR.html',1,'rabit::op']]],
  ['bitxor_51',['BitXOR',['../structrabit_1_1op_1_1BitXOR.html',1,'rabit::op']]],
  ['blob_52',['Blob',['../structdmlc_1_1InputSplit_1_1Blob.html',1,'dmlc::InputSplit']]],
  ['blockedspace2d_53',['BlockedSpace2d',['../classxgboost_1_1common_1_1BlockedSpace2d.html',1,'xgboost::common']]],
  ['blockinfo_54',['BlockInfo',['../structxgboost_1_1common_1_1PartitionBuilder_1_1BlockInfo.html',1,'xgboost::common::PartitionBuilder']]],
  ['blockingqueuethread_55',['BlockingQueueThread',['../classdmlc_1_1BlockingQueueThread.html',1,'dmlc']]],
  ['booster_56',['booster',['../classlightgbm_1_1basic_1_1Booster.html',1,'lightgbm.basic.Booster'],['../classLightGBM_1_1Booster.html',1,'LightGBM::Booster'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1Booster.html',1,'ml.dmlc.xgboost4j.java.Booster'],['../classxgboost_1_1core_1_1Booster.html',1,'xgboost.core.Booster']]],
  ['boosterimpltest_57',['BoosterImplTest',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1BoosterImplTest.html',1,'ml::dmlc::xgboost4j::java']]],
  ['boostertest_58',['BoosterTest',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1BoosterTest.html',1,'ml::dmlc::xgboost4j::gpu::java']]],
  ['boostfromprediction_59',['BoostFromPrediction',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1BoostFromPrediction.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['boosting_60',['Boosting',['../classLightGBM_1_1Boosting.html',1,'LightGBM']]],
  ['boundedhistcollection_61',['BoundedHistCollection',['../classxgboost_1_1tree_1_1BoundedHistCollection.html',1,'xgboost::tree']]],
  ['broadcastfunctor_62',['BroadcastFunctor',['../classxgboost_1_1collective_1_1BroadcastFunctor.html',1,'xgboost::collective']]],
  ['bruckmap_63',['BruckMap',['../classLightGBM_1_1BruckMap.html',1,'LightGBM']]],
  ['buildconfiguration_64',['BuildConfiguration',['../classpackager_1_1build__config_1_1BuildConfiguration.html',1,'packager::build_config']]],
  ['builder_65',['Builder',['../classxgboost_1_1tree_1_1ColMaker_1_1Builder.html',1,'xgboost::tree::ColMaker']]]
];
