var searchData=
[
  ['dart_0',['dart',['../classxgboost_1_1gbm_1_1Dart.html',1,'xgboost::gbm::Dart'],['../classLightGBM_1_1DART.html',1,'LightGBM::DART']]],
  ['darttrainparam_1',['DartTrainParam',['../structxgboost_1_1gbm_1_1DartTrainParam.html',1,'xgboost::gbm']]],
  ['daskdevicequantiledmatrix_2',['DaskDeviceQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskDeviceQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskdmatrix_3',['DaskDMatrix',['../classxgboost_1_1dask_1_1DaskDMatrix.html',1,'xgboost::dask']]],
  ['daskpartitioniter_4',['DaskPartitionIter',['../classxgboost_1_1dask_1_1DaskPartitionIter.html',1,'xgboost::dask']]],
  ['daskquantiledmatrix_5',['DaskQuantileDMatrix',['../classxgboost_1_1dask_1_1DaskQuantileDMatrix.html',1,'xgboost::dask']]],
  ['daskscikitlearnbase_6',['DaskScikitLearnBase',['../classxgboost_1_1dask_1_1DaskScikitLearnBase.html',1,'xgboost::dask']]],
  ['daskxgbclassifier_7',['DaskXGBClassifier',['../classxgboost_1_1dask_1_1DaskXGBClassifier.html',1,'xgboost::dask']]],
  ['daskxgbranker_8',['DaskXGBRanker',['../classxgboost_1_1dask_1_1DaskXGBRanker.html',1,'xgboost::dask']]],
  ['daskxgbregressor_9',['DaskXGBRegressor',['../classxgboost_1_1dask_1_1DaskXGBRegressor.html',1,'xgboost::dask']]],
  ['daskxgbrfclassifier_10',['DaskXGBRFClassifier',['../classxgboost_1_1dask_1_1DaskXGBRFClassifier.html',1,'xgboost::dask']]],
  ['daskxgbrfregressor_11',['DaskXGBRFRegressor',['../classxgboost_1_1dask_1_1DaskXGBRFRegressor.html',1,'xgboost::dask']]],
  ['dataframe_12',['DataFrame',['../classlightgbm_1_1compat_1_1DataFrame.html',1,'lightgbm::compat']]],
  ['dataiter_13',['dataiter',['../classdmlc_1_1DataIter.html',1,'dmlc::DataIter&lt; DType &gt;'],['../classxgboost_1_1core_1_1DataIter.html',1,'xgboost.core.DataIter']]],
  ['dataiter_3c_20arrayadapterbatch_20_3e_14',['DataIter&lt; ArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20arrowcolumnarbatchvec_20_3e_15',['DataIter&lt; ArrowColumnarBatchVec &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscadapterbatch_20_3e_16',['DataIter&lt; CSCAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20cscarrayadapterbatch_20_3e_17',['DataIter&lt; CSCArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csradapterbatch_20_3e_18',['DataIter&lt; CSRAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20csrarrayadapterbatch_20_3e_19',['DataIter&lt; CSRArrayAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20datatableadapterbatch_20_3e_20',['DataIter&lt; DataTableAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20denseadapterbatch_20_3e_21',['DataIter&lt; DenseAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20fileadapterbatch_20_3e_22',['DataIter&lt; FileAdapterBatch &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20indextype_2c_20real_5ft_20_3e_20_3e_23',['DataIter&lt; RowBlock&lt; IndexType, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiter_3c_20rowblock_3c_20uint32_5ft_2c_20real_5ft_20_3e_20_3e_24',['DataIter&lt; RowBlock&lt; uint32_t, real_t &gt; &gt;',['../classdmlc_1_1DataIter.html',1,'dmlc']]],
  ['dataiterproxy_25',['DataIterProxy',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['dataiterproxy_3c_20dataiterresetcallback_2c_20xgdmatrixcallbacknext_20_3e_26',['DataIterProxy&lt; DataIterResetCallback, XGDMatrixCallbackNext &gt;',['../classxgboost_1_1data_1_1DataIterProxy.html',1,'xgboost::data']]],
  ['dataloader_27',['dataloader',['../classCommonTestingTools_1_1DataLoader.html',1,'CommonTestingTools::DataLoader'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1util_1_1DataLoader.html',1,'ml.dmlc.xgboost4j.java.example.util.DataLoader']]],
  ['dataparalleltreelearner_28',['DataParallelTreeLearner',['../classLightGBM_1_1DataParallelTreeLearner.html',1,'LightGBM']]],
  ['datapartition_29',['DataPartition',['../classLightGBM_1_1DataPartition.html',1,'LightGBM']]],
  ['dataset_30',['dataset',['../classLightGBM_1_1Dataset.html',1,'LightGBM::Dataset'],['../classlightgbm_1_1basic_1_1Dataset.html',1,'lightgbm.basic.Dataset']]],
  ['datasetloader_31',['DatasetLoader',['../classLightGBM_1_1DatasetLoader.html',1,'LightGBM']]],
  ['datasplitmode_32',['DataSplitMode',['../classxgboost_1_1core_1_1DataSplitMode.html',1,'xgboost::core']]],
  ['datatable_33',['DataTable',['../classlightgbm_1_1compat_1_1DataTable.html',1,'lightgbm::compat']]],
  ['datatableadapter_34',['DataTableAdapter',['../classxgboost_1_1data_1_1DataTableAdapter.html',1,'xgboost::data']]],
  ['datatableadapterbatch_35',['DataTableAdapterBatch',['../classxgboost_1_1data_1_1DataTableAdapterBatch.html',1,'xgboost::data']]],
  ['datatype_36',['datatype',['../enumml_1_1dmlc_1_1xgboost4j_1_1java_1_1Communicator_1_1DataType.html',1,'ml.dmlc.xgboost4j.java.Communicator.DataType'],['../classMPI_1_1Datatype.html',1,'MPI::Datatype']]],
  ['datelogger_37',['DateLogger',['../classdmlc_1_1DateLogger.html',1,'dmlc']]],
  ['dbl_5fidx_38',['dbl_idx',['../structdbl__idx.html',1,'']]],
  ['dcgcalculator_39',['DCGCalculator',['../classLightGBM_1_1DCGCalculator.html',1,'LightGBM']]],
  ['decision_5ffunction_40',['decision_function',['../structdecision__function.html',1,'']]],
  ['dense4bitsbin_41',['Dense4bitsBin',['../classLightGBM_1_1Dense4bitsBin.html',1,'LightGBM']]],
  ['dense4bitsbiniterator_42',['Dense4bitsBinIterator',['../classLightGBM_1_1Dense4bitsBinIterator.html',1,'LightGBM']]],
  ['denseadapter_43',['DenseAdapter',['../classxgboost_1_1data_1_1DenseAdapter.html',1,'xgboost::data']]],
  ['denseadapterbatch_44',['DenseAdapterBatch',['../classxgboost_1_1data_1_1DenseAdapterBatch.html',1,'xgboost::data']]],
  ['densebin_45',['DenseBin',['../classLightGBM_1_1DenseBin.html',1,'LightGBM']]],
  ['densebiniterator_46',['DenseBinIterator',['../classLightGBM_1_1DenseBinIterator.html',1,'LightGBM']]],
  ['densecolumniter_47',['DenseColumnIter',['../classxgboost_1_1common_1_1DenseColumnIter.html',1,'xgboost::common']]],
  ['densifyparser_48',['DensifyParser',['../classdmlc_1_1data_1_1DensifyParser.html',1,'dmlc::data']]],
  ['deprecatedgblinearmodelparam_49',['DeprecatedGBLinearModelParam',['../structxgboost_1_1gbm_1_1DeprecatedGBLinearModelParam.html',1,'xgboost::gbm']]],
  ['derivedclass_50',['DerivedClass',['../structxgboost_1_1common_1_1DerivedClass.html',1,'xgboost::common']]],
  ['deviceauccache_51',['DeviceAUCCache',['../structxgboost_1_1metric_1_1DeviceAUCCache.html',1,'xgboost::metric']]],
  ['devicematrixoneapi_52',['DeviceMatrixOneAPI',['../structxgboost_1_1predictor_1_1DeviceMatrixOneAPI.html',1,'xgboost::predictor']]],
  ['devicemodeloneapi_53',['DeviceModelOneAPI',['../classxgboost_1_1predictor_1_1DeviceModelOneAPI.html',1,'xgboost::predictor']]],
  ['devicenodeoneapi_54',['DeviceNodeOneAPI',['../structxgboost_1_1predictor_1_1DeviceNodeOneAPI.html',1,'xgboost::predictor']]],
  ['deviceord_55',['DeviceOrd',['../structxgboost_1_1DeviceOrd.html',1,'xgboost']]],
  ['devicequantiledmatrix_56',['DeviceQuantileDMatrix',['../classxgboost_1_1core_1_1DeviceQuantileDMatrix.html',1,'xgboost::core']]],
  ['devicesym_57',['DeviceSym',['../structxgboost_1_1DeviceSym.html',1,'xgboost']]],
  ['dgnrtfeatureremvoer_58',['DgnrtFeatureRemvoer',['../classDgnrtFeatureRemvoer.html',1,'']]],
  ['diabetesfindergenerator_59',['DiabetesFinderGenerator',['../classDiabetesFinderGenerator.html',1,'']]],
  ['differentversionsiterator_60',['differentVersionsIterator',['../classdifferentVersionsIterator.html',1,'']]],
  ['directoryexcursion_61',['directoryexcursion',['../classrelease-artifacts_1_1DirectoryExcursion.html',1,'release-artifacts.DirectoryExcursion'],['../classxgboost_1_1testing_1_1DirectoryExcursion.html',1,'xgboost.testing.DirectoryExcursion'],['../classtest__utils_1_1DirectoryExcursion.html',1,'test_utils.DirectoryExcursion']]],
  ['disttrainwithflinkexample_62',['DistTrainWithFlinkExample',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1flink_1_1DistTrainWithFlinkExample.html',1,'ml::dmlc::xgboost4j::java::example::flink']]],
  ['dmatrix_63',['dmatrix',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrix.html',1,'ml.dmlc.xgboost4j.java.DMatrix'],['../classxgboost_1_1core_1_1DMatrix.html',1,'xgboost.core.DMatrix'],['../classxgboost_1_1DMatrix.html',1,'xgboost::DMatrix']]],
  ['dmatrixcache_64',['DMatrixCache',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20cache_20_3e_65',['DMatrixCache&lt; Cache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3amapcache_20_3e_66',['DMatrixCache&lt; ltr::MAPCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3andcgcache_20_3e_67',['DMatrixCache&lt; ltr::NDCGCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20ltr_3a_3aprecache_20_3e_68',['DMatrixCache&lt; ltr::PreCache &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixcache_3c_20predictioncacheentry_20_3e_69',['DMatrixCache&lt; PredictionCacheEntry &gt;',['../classxgboost_1_1DMatrixCache.html',1,'xgboost']]],
  ['dmatrixproxy_70',['DMatrixProxy',['../classxgboost_1_1data_1_1DMatrixProxy.html',1,'xgboost::data']]],
  ['dmatrixtest_71',['dmatrixtest',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.gpu.java.DMatrixTest'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1DMatrixTest.html',1,'ml.dmlc.xgboost4j.java.DMatrixTest']]],
  ['docalcfeatprocessor_72',['DoCalcFeatProcessor',['../classDoCalcFeatProcessor.html',1,'']]],
  ['driver_73',['Driver',['../classxgboost_1_1tree_1_1Driver.html',1,'xgboost::tree']]],
  ['drugintakegenerator_74',['DrugIntakeGenerator',['../classDrugIntakeGenerator.html',1,'']]],
  ['drugsheatmapparams_75',['DrugsHeatMapParams',['../classDrugsHeatMapParams.html',1,'']]],
  ['duplicateprocessor_76',['DuplicateProcessor',['../classDuplicateProcessor.html',1,'']]],
  ['dynam_77',['DynAM',['../classDynAM.html',1,'']]]
];
