var searchData=
[
  ['cache_0',['cache',['../structxgboost_1_1data_1_1Cache.html',1,'xgboost.data::Cache'],['../classCache.html',1,'Cache']]],
  ['calibration_5fentry_1',['calibration_entry',['../classcalibration__entry.html',1,'']]],
  ['calibrator_2',['Calibrator',['../classCalibrator.html',1,'']]],
  ['callbackcontainer_3',['CallbackContainer',['../classxgboost_1_1callback_1_1CallbackContainer.html',1,'xgboost::callback']]],
  ['candidate_5fcompare_4',['candidate_compare',['../structcandidate__compare.html',1,'']]],
  ['categoricalsplitmatrix_5',['CategoricalSplitMatrix',['../structxgboost_1_1RegTree_1_1CategoricalSplitMatrix.html',1,'xgboost::RegTree']]],
  ['category_5fevent_5fstate_6',['category_event_state',['../structcategory__event__state.html',1,'']]],
  ['category_5ftime_5finterval_7',['category_time_interval',['../structcategory__time__interval.html',1,'']]],
  ['categorydependencygenerator_8',['CategoryDependencyGenerator',['../classCategoryDependencyGenerator.html',1,'']]],
  ['chan_5finfo_9',['chan_info',['../structchan__info.html',1,'']]],
  ['changemodelinfo_10',['ChangeModelInfo',['../classChangeModelInfo.html',1,'']]],
  ['charpp_5fadaptor_11',['charpp_adaptor',['../classCommonTestingTools_1_1charpp__adaptor.html',1,'CommonTestingTools']]],
  ['charttimesign_12',['ChartTimeSign',['../classChartTimeSign.html',1,'']]],
  ['chunk_13',['Chunk',['../structdmlc_1_1io_1_1InputSplitBase_1_1Chunk.html',1,'dmlc::io::InputSplitBase']]],
  ['clangtidy_14',['ClangTidy',['../classtidy_1_1ClangTidy.html',1,'tidy']]],
  ['cli_15',['CLI',['../classxgboost_1_1CLI.html',1,'xgboost']]],
  ['clickfold_16',['ClickFold',['../classxgboost_1_1testing_1_1data_1_1ClickFold.html',1,'xgboost::testing::data']]],
  ['client_17',['Client',['../classorg_1_1apache_1_1hadoop_1_1yarn_1_1dmlc_1_1Client.html',1,'org::apache::hadoop::yarn::dmlc']]],
  ['cliparam_18',['CLIParam',['../structxgboost_1_1CLIParam.html',1,'xgboost']]],
  ['cmakebuild_19',['CMakeBuild',['../classsetup_1_1CMakeBuild.html',1,'setup']]],
  ['cmakeextension_20',['CMakeExtension',['../classsetup_1_1CMakeExtension.html',1,'setup']]],
  ['cohortrec_21',['CohortRec',['../structCohortRec.html',1,'']]],
  ['collected_5fdata_22',['collected_data',['../classcollected__data.html',1,'']]],
  ['colmaker_23',['ColMaker',['../classxgboost_1_1tree_1_1ColMaker.html',1,'xgboost::tree']]],
  ['colmakertrainparam_24',['ColMakerTrainParam',['../structxgboost_1_1tree_1_1ColMakerTrainParam.html',1,'xgboost::tree']]],
  ['column_25',['column',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1Column.html',1,'ml.dmlc.xgboost4j.java.Column'],['../classxgboost_1_1common_1_1Column.html',1,'xgboost::common::Column&lt; BinIdxType &gt;'],['../classxgboost_1_1data_1_1Column.html',1,'xgboost.data::Column']]],
  ['column_3c_20binidxt_20_3e_26',['Column&lt; BinIdxT &gt;',['../classxgboost_1_1common_1_1Column.html',1,'xgboost::common']]],
  ['columnarmetainfo_27',['ColumnarMetaInfo',['../structxgboost_1_1data_1_1ColumnarMetaInfo.html',1,'xgboost::data']]],
  ['columnbatch_28',['ColumnBatch',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1ColumnBatch.html',1,'ml::dmlc::xgboost4j::java']]],
  ['columnmatrix_29',['ColumnMatrix',['../classxgboost_1_1common_1_1ColumnMatrix.html',1,'xgboost::common']]],
  ['columnsampler_30',['ColumnSampler',['../classxgboost_1_1common_1_1ColumnSampler.html',1,'xgboost::common']]],
  ['columnsplithelper_31',['columnsplithelper',['../classxgboost_1_1predictor_1_1ColumnSplitHelper.html',1,'xgboost::predictor::ColumnSplitHelper'],['../classxgboost_1_1tree_1_1ColumnSplitHelper.html',1,'xgboost::tree::ColumnSplitHelper']]],
  ['combination_5fstate_32',['combination_state',['../structcombination__state.html',1,'']]],
  ['commonrowpartitioner_33',['CommonRowPartitioner',['../classxgboost_1_1tree_1_1CommonRowPartitioner.html',1,'xgboost::tree']]],
  ['communicator_34',['communicator',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1Communicator.html',1,'ml.dmlc.xgboost4j.java.Communicator'],['../classxgboost_1_1collective_1_1Communicator.html',1,'xgboost::collective::Communicator']]],
  ['communicatorcontext_35',['communicatorcontext',['../classxgboost_1_1collective_1_1CommunicatorContext.html',1,'xgboost.collective.CommunicatorContext'],['../classxgboost_1_1dask_1_1CommunicatorContext.html',1,'xgboost.dask.CommunicatorContext'],['../classxgboost_1_1spark_1_1utils_1_1CommunicatorContext.html',1,'xgboost.spark.utils.CommunicatorContext']]],
  ['compactindexelem_36',['CompactIndexElem',['../classCompactIndexElem.html',1,'']]],
  ['compare_5findexed_5ffloat_37',['compare_indexed_float',['../structcompare__indexed__float.html',1,'']]],
  ['comparepairbyfirst_38',['ComparePairByFirst',['../structComparePairByFirst.html',1,'']]],
  ['comparepairbysecond_39',['ComparePairBySecond',['../structComparePairBySecond.html',1,'']]],
  ['compressbin_40',['CompressBin',['../structxgboost_1_1common_1_1Index_1_1CompressBin.html',1,'xgboost::common::Index']]],
  ['compressedbufferwriter_41',['CompressedBufferWriter',['../classxgboost_1_1common_1_1CompressedBufferWriter.html',1,'xgboost::common']]],
  ['compressediterator_42',['CompressedIterator',['../classxgboost_1_1common_1_1CompressedIterator.html',1,'xgboost::common']]],
  ['conf_43',['conf',['../classlearn_1_1conf.html',1,'learn']]],
  ['config_44',['config',['../classdmlc_1_1Config.html',1,'dmlc::Config'],['../structLightGBM_1_1Config.html',1,'LightGBM::Config']]],
  ['configiterator_45',['ConfigIterator',['../classdmlc_1_1Config_1_1ConfigIterator.html',1,'dmlc::Config']]],
  ['configparser_46',['ConfigParser',['../classxgboost_1_1common_1_1ConfigParser.html',1,'xgboost::common']]],
  ['configurable_47',['Configurable',['../structxgboost_1_1Configurable.html',1,'xgboost']]],
  ['confrecord_48',['confRecord',['../classconfRecord.html',1,'']]],
  ['conjunction_49',['conjunction',['../structxgboost_1_1linalg_1_1detail_1_1Conjunction.html',1,'xgboost::linalg::detail::Conjunction&lt;... &gt;'],['../structdetail_1_1conjunction.html',1,'detail::conjunction&lt;... &gt;']]],
  ['conjunction_3c_20b_20_3e_50',['conjunction&lt; B &gt;',['../structdetail_1_1conjunction_3_01B_01_4.html',1,'detail']]],
  ['conjunction_3c_20b_2c_20bn_2e_2e_2e_20_3e_51',['conjunction&lt; B, Bn... &gt;',['../structdetail_1_1conjunction_3_01B_00_01Bn_8_8_8_01_4.html',1,'detail']]],
  ['conjunction_3c_20b1_20_3e_52',['Conjunction&lt; B1 &gt;',['../structxgboost_1_1linalg_1_1detail_1_1Conjunction_3_01B1_01_4.html',1,'xgboost::linalg::detail']]],
  ['conjunction_3c_20b1_2c_20bn_2e_2e_2e_20_3e_53',['Conjunction&lt; B1, Bn... &gt;',['../structxgboost_1_1linalg_1_1detail_1_1Conjunction_3_01B1_00_01Bn_8_8_8_01_4.html',1,'xgboost::linalg::detail']]],
  ['conjunction_3c_20is_5fconstructible_3c_20t1_2c_20args_20_3e_2e_2e_2e_20_3e_54',['conjunction&lt; is_constructible&lt; T1, Args &gt;... &gt;',['../structdetail_1_1conjunction.html',1,'detail']]],
  ['conjunction_3c_20is_5fdefault_5fconstructible_3c_20t1_20_3e_2c_20is_5fdefault_5fconstructible_3c_20t2_20_3e_20_3e_55',['conjunction&lt; is_default_constructible&lt; T1 &gt;, is_default_constructible&lt; T2 &gt; &gt;',['../structdetail_1_1conjunction.html',1,'detail']]],
  ['conjunction_3c_20is_5fdefault_5fconstructible_3c_20ts_20_3e_2e_2e_2e_20_3e_56',['conjunction&lt; is_default_constructible&lt; Ts &gt;... &gt;',['../structdetail_1_1conjunction.html',1,'detail']]],
  ['consolelogger_57',['ConsoleLogger',['../classxgboost_1_1ConsoleLogger.html',1,'xgboost']]],
  ['constantvaluecalculator_58',['ConstantValueCalculator',['../classConstantValueCalculator.html',1,'']]],
  ['container_5finput_5fadapter_5ffactory_59',['container_input_adapter_factory',['../structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html',1,'detail::container_input_adapter_factory_impl']]],
  ['container_5finput_5fadapter_5ffactory_3c_20containertype_2c_20void_5ft_3c_20decltype_28begin_28std_3a_3adeclval_3c_20containertype_20_3e_28_29_29_2c_20end_28std_3a_3adeclval_3c_20containertype_20_3e_28_29_29_29_3e_20_3e_60',['container_input_adapter_factory&lt; ContainerType, void_t&lt; decltype(begin(std::declval&lt; ContainerType &gt;()), end(std::declval&lt; ContainerType &gt;()))&gt; &gt;',['../structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3983614ac0e8828aa386ca24b1ddc2bd1.html',1,'detail::container_input_adapter_factory_impl']]],
  ['context_61',['Context',['../structxgboost_1_1Context.html',1,'xgboost']]],
  ['coordinateparam_62',['CoordinateParam',['../structxgboost_1_1linear_1_1CoordinateParam.html',1,'xgboost::linear']]],
  ['coordinateupdater_63',['CoordinateUpdater',['../classxgboost_1_1linear_1_1CoordinateUpdater.html',1,'xgboost::linear']]],
  ['cootuple_64',['COOTuple',['../structxgboost_1_1data_1_1COOTuple.html',1,'xgboost::data']]],
  ['copyuniqueptr_65',['CopyUniquePtr',['../classxgboost_1_1CopyUniquePtr.html',1,'xgboost']]],
  ['copyuniqueptr_3c_20xgboost_3a_3amultitargettree_20_3e_66',['CopyUniquePtr&lt; xgboost::MultiTargetTree &gt;',['../classxgboost_1_1CopyUniquePtr.html',1,'xgboost']]],
  ['cpuexpandentry_67',['CPUExpandEntry',['../structxgboost_1_1tree_1_1CPUExpandEntry.html',1,'xgboost::tree']]],
  ['cpupredictor_68',['CPUPredictor',['../classxgboost_1_1predictor_1_1CPUPredictor.html',1,'xgboost::predictor']]],
  ['crossentropy_69',['CrossEntropy',['../classLightGBM_1_1CrossEntropy.html',1,'LightGBM']]],
  ['crossentropylambda_70',['CrossEntropyLambda',['../classLightGBM_1_1CrossEntropyLambda.html',1,'LightGBM']]],
  ['crossentropylambdametric_71',['CrossEntropyLambdaMetric',['../classLightGBM_1_1CrossEntropyLambdaMetric.html',1,'LightGBM']]],
  ['crossentropymetric_72',['CrossEntropyMetric',['../classLightGBM_1_1CrossEntropyMetric.html',1,'LightGBM']]],
  ['crossvalidation_73',['CrossValidation',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1CrossValidation.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['crossvalidator_74',['CrossValidator',['../classCrossValidator.html',1,'']]],
  ['csc_5frowiterator_75',['CSC_RowIterator',['../classCSC__RowIterator.html',1,'']]],
  ['cscadapter_76',['CSCAdapter',['../classxgboost_1_1data_1_1CSCAdapter.html',1,'xgboost::data']]],
  ['cscadapterbatch_77',['CSCAdapterBatch',['../classxgboost_1_1data_1_1CSCAdapterBatch.html',1,'xgboost::data']]],
  ['cscarrayadapter_78',['CSCArrayAdapter',['../classxgboost_1_1data_1_1CSCArrayAdapter.html',1,'xgboost::data']]],
  ['cscarrayadapterbatch_79',['CSCArrayAdapterBatch',['../classxgboost_1_1data_1_1CSCArrayAdapterBatch.html',1,'xgboost::data']]],
  ['cscpage_80',['CSCPage',['../classxgboost_1_1CSCPage.html',1,'xgboost']]],
  ['cscpagesource_81',['CSCPageSource',['../classxgboost_1_1data_1_1CSCPageSource.html',1,'xgboost::data']]],
  ['csradapter_82',['CSRAdapter',['../classxgboost_1_1data_1_1CSRAdapter.html',1,'xgboost::data']]],
  ['csradapterbatch_83',['CSRAdapterBatch',['../classxgboost_1_1data_1_1CSRAdapterBatch.html',1,'xgboost::data']]],
  ['csrarrayadapter_84',['CSRArrayAdapter',['../classxgboost_1_1data_1_1CSRArrayAdapter.html',1,'xgboost::data']]],
  ['csrarrayadapterbatch_85',['CSRArrayAdapterBatch',['../classxgboost_1_1data_1_1CSRArrayAdapterBatch.html',1,'xgboost::data']]],
  ['csriterfortest_86',['CSRIterForTest',['../classxgboost_1_1CSRIterForTest.html',1,'xgboost']]],
  ['csvparser_87',['csvparser',['../classdmlc_1_1data_1_1CSVParser.html',1,'dmlc::data::CSVParser&lt; IndexType, DType &gt;'],['../classLightGBM_1_1CSVParser.html',1,'LightGBM::CSVParser']]],
  ['csvparser_3c_20indextype_2c_20real_5ft_20_3e_88',['CSVParser&lt; IndexType, real_t &gt;',['../classdmlc_1_1data_1_1CSVParser.html',1,'dmlc::data']]],
  ['csvparserparam_89',['CSVParserParam',['../structdmlc_1_1data_1_1CSVParserParam.html',1,'dmlc::data']]],
  ['csvparsertest_90',['CSVParserTest',['../classparser__test_1_1CSVParserTest.html',1,'parser_test']]],
  ['cudaarrayiterfortest_91',['CudaArrayIterForTest',['../classxgboost_1_1CudaArrayIterForTest.html',1,'xgboost']]],
  ['cudfcolumn_92',['CudfColumn',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1CudfColumn.html',1,'ml::dmlc::xgboost4j::gpu::java']]],
  ['cudfcolumnbatch_93',['CudfColumnBatch',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1CudfColumnBatch.html',1,'ml::dmlc::xgboost4j::gpu::java']]],
  ['curlglobal_94',['CURLGlobal',['../structdmlc_1_1io_1_1s3_1_1CURLGlobal.html',1,'dmlc::io::s3']]],
  ['curlreadstreambase_95',['CURLReadStreamBase',['../classdmlc_1_1io_1_1s3_1_1CURLReadStreamBase.html',1,'dmlc::io::s3']]],
  ['custombuildhook_96',['CustomBuildHook',['../classhatch__build_1_1CustomBuildHook.html',1,'hatch_build']]],
  ['customearlystopping_97',['CustomEarlyStopping',['../classdask__callbacks_1_1CustomEarlyStopping.html',1,'dask_callbacks']]],
  ['customeval_98',['CustomEval',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1util_1_1CustomEval.html',1,'ml::dmlc::xgboost4j::java::example::util']]],
  ['custominstall_99',['CustomInstall',['../classsetup_1_1CustomInstall.html',1,'setup']]],
  ['custominstalllib_100',['CustomInstallLib',['../classsetup_1_1CustomInstallLib.html',1,'setup']]],
  ['customlogmessage_101',['CustomLogMessage',['../classdmlc_1_1CustomLogMessage.html',1,'dmlc']]],
  ['customobjective_102',['CustomObjective',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1CustomObjective.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['customsdist_103',['CustomSdist',['../classsetup_1_1CustomSdist.html',1,'setup']]],
  ['cutoff_5fconstraint_104',['Cutoff_Constraint',['../classCutoff__Constraint.html',1,'']]],
  ['cvpack_105',['CVPack',['../classxgboost_1_1training_1_1CVPack.html',1,'xgboost::training']]],
  ['cyclicfeatureselector_106',['CyclicFeatureSelector',['../classxgboost_1_1linear_1_1CyclicFeatureSelector.html',1,'xgboost::linear']]]
];
