var searchData=
[
  ['bart_0',['BART',['../classBART.html',1,'']]],
  ['bart_5fnode_1',['bart_node',['../classbart__node.html',1,'']]],
  ['bart_5fparams_2',['bart_params',['../classbart__params.html',1,'']]],
  ['bart_5ftree_3',['bart_tree',['../classbart__tree.html',1,'']]],
  ['base64instream_4',['Base64InStream',['../classxgboost_1_1common_1_1Base64InStream.html',1,'xgboost::common']]],
  ['base64outstream_5',['Base64OutStream',['../classxgboost_1_1common_1_1Base64OutStream.html',1,'xgboost::common']]],
  ['baseclass_6',['BaseClass',['../structxgboost_1_1common_1_1BaseClass.html',1,'xgboost::common']]],
  ['basefederatedtest_7',['BaseFederatedTest',['../classxgboost_1_1BaseFederatedTest.html',1,'xgboost']]],
  ['baselogger_8',['BaseLogger',['../classxgboost_1_1BaseLogger.html',1,'xgboost']]],
  ['basemgputest_9',['BaseMGPUTest',['../classxgboost_1_1BaseMGPUTest.html',1,'xgboost']]],
  ['basic_5fjson_10',['basic_json',['../classbasic__json.html',1,'']]],
  ['basicfeatgenerator_11',['BasicFeatGenerator',['../classBasicFeatGenerator.html',1,'']]],
  ['basicfilteringparams_12',['BasicFilteringParams',['../structBasicFilteringParams.html',1,'']]],
  ['basicrowiter_13',['BasicRowIter',['../classdmlc_1_1data_1_1BasicRowIter.html',1,'dmlc::data']]],
  ['basicsamplefilter_14',['BasicSampleFilter',['../classBasicSampleFilter.html',1,'']]],
  ['basictestfilter_15',['BasicTestFilter',['../classBasicTestFilter.html',1,'']]],
  ['basictrainfilter_16',['BasicTrainFilter',['../classBasicTrainFilter.html',1,'']]],
  ['basicwalkthrough_17',['BasicWalkThrough',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1BasicWalkThrough.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['batchiterator_18',['BatchIterator',['../classxgboost_1_1BatchIterator.html',1,'xgboost']]],
  ['batchiteratorimpl_19',['BatchIteratorImpl',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20cscpage_20_3e_20',['BatchIteratorImpl&lt; CSCPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20ellpackpage_20_3e_21',['BatchIteratorImpl&lt; EllpackPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20ghistindexmatrix_20_3e_22',['BatchIteratorImpl&lt; GHistIndexMatrix &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20s_20_3e_23',['BatchIteratorImpl&lt; S &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20sortedcscpage_20_3e_24',['BatchIteratorImpl&lt; SortedCSCPage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchiteratorimpl_3c_20sparsepage_20_3e_25',['BatchIteratorImpl&lt; SparsePage &gt;',['../classxgboost_1_1BatchIteratorImpl.html',1,'xgboost']]],
  ['batchparam_26',['BatchParam',['../structxgboost_1_1BatchParam.html',1,'xgboost']]],
  ['batchset_27',['BatchSet',['../classxgboost_1_1BatchSet.html',1,'xgboost']]],
  ['bigdensematrix_28',['BigDenseMatrix',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1util_1_1BigDenseMatrix.html',1,'ml::dmlc::xgboost4j::java::util']]],
  ['bin_29',['Bin',['../classLightGBM_1_1Bin.html',1,'LightGBM']]],
  ['binary_5freader_30',['binary_reader',['../classdetail_1_1binary__reader.html',1,'detail']]],
  ['binaryerrormetric_31',['BinaryErrorMetric',['../classLightGBM_1_1BinaryErrorMetric.html',1,'LightGBM']]],
  ['binarylogloss_32',['BinaryLogloss',['../classLightGBM_1_1BinaryLogloss.html',1,'LightGBM']]],
  ['binaryloglossmetric_33',['BinaryLoglossMetric',['../classLightGBM_1_1BinaryLoglossMetric.html',1,'LightGBM']]],
  ['binarymetric_34',['BinaryMetric',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarymetric_3c_20binaryerrormetric_20_3e_35',['BinaryMetric&lt; BinaryErrorMetric &gt;',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarymetric_3c_20binaryloglossmetric_20_3e_36',['BinaryMetric&lt; BinaryLoglossMetric &gt;',['../classLightGBM_1_1BinaryMetric.html',1,'LightGBM']]],
  ['binarytree_37',['BinaryTree',['../structtree_1_1BinaryTree.html',1,'tree']]],
  ['biniterator_38',['BinIterator',['../classLightGBM_1_1BinIterator.html',1,'LightGBM']]],
  ['binmapper_39',['BinMapper',['../classLightGBM_1_1BinMapper.html',1,'LightGBM']]],
  ['binnedlmestimates_40',['BinnedLmEstimates',['../classBinnedLmEstimates.html',1,'']]],
  ['binnedlmestimatesparams_41',['BinnedLmEstimatesParams',['../structBinnedLmEstimatesParams.html',1,'']]],
  ['binning_5fwrapper_42',['Binning_Wrapper',['../classBinning__Wrapper.html',1,'']]],
  ['binningfeatprocessor_43',['BinningFeatProcessor',['../classBinningFeatProcessor.html',1,'']]],
  ['binsettings_44',['BinSettings',['../classBinSettings.html',1,'']]],
  ['binsplitoptimizer_45',['BinSplitOptimizer',['../classBinSplitOptimizer.html',1,'']]],
  ['bitand_46',['BitAND',['../structrabit_1_1op_1_1BitAND.html',1,'rabit::op']]],
  ['bitfieldcontainer_47',['BitFieldContainer',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20uint32_5ft_2c_20lbitspolicy_3c_20uint32_5ft_20_3e_20_3e_48',['BitFieldContainer&lt; uint32_t, LBitsPolicy&lt; uint32_t &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20uint8_5ft_2c_20rbitspolicy_3c_20unsigned_20char_20_3e_20_3e_49',['BitFieldContainer&lt; uint8_t, RBitsPolicy&lt; unsigned char &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20vt_2c_20lbitspolicy_3c_20vt_2c_20false_20_3e_2c_20false_20_3e_50',['BitFieldContainer&lt; VT, LBitsPolicy&lt; VT, false &gt;, false &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitfieldcontainer_3c_20vt_2c_20rbitspolicy_3c_20vt_20_3e_20_3e_51',['BitFieldContainer&lt; VT, RBitsPolicy&lt; VT &gt; &gt;',['../structxgboost_1_1BitFieldContainer.html',1,'xgboost']]],
  ['bitor_52',['BitOR',['../structrabit_1_1op_1_1BitOR.html',1,'rabit::op']]],
  ['bitxor_53',['BitXOR',['../structrabit_1_1op_1_1BitXOR.html',1,'rabit::op']]],
  ['blob_54',['Blob',['../structdmlc_1_1InputSplit_1_1Blob.html',1,'dmlc::InputSplit']]],
  ['blockedspace2d_55',['BlockedSpace2d',['../classxgboost_1_1common_1_1BlockedSpace2d.html',1,'xgboost::common']]],
  ['blockinfo_56',['BlockInfo',['../structxgboost_1_1common_1_1PartitionBuilder_1_1BlockInfo.html',1,'xgboost::common::PartitionBuilder']]],
  ['blockingqueuethread_57',['BlockingQueueThread',['../classdmlc_1_1BlockingQueueThread.html',1,'dmlc']]],
  ['booster_58',['booster',['../classlightgbm_1_1basic_1_1Booster.html',1,'lightgbm.basic.Booster'],['../classLightGBM_1_1Booster.html',1,'LightGBM::Booster'],['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1Booster.html',1,'ml.dmlc.xgboost4j.java.Booster'],['../classxgboost_1_1core_1_1Booster.html',1,'xgboost.core.Booster']]],
  ['boosterimpltest_59',['BoosterImplTest',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1BoosterImplTest.html',1,'ml::dmlc::xgboost4j::java']]],
  ['boostertest_60',['BoosterTest',['../classml_1_1dmlc_1_1xgboost4j_1_1gpu_1_1java_1_1BoosterTest.html',1,'ml::dmlc::xgboost4j::gpu::java']]],
  ['boostfromprediction_61',['BoostFromPrediction',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1example_1_1BoostFromPrediction.html',1,'ml::dmlc::xgboost4j::java::example']]],
  ['boosting_62',['Boosting',['../classLightGBM_1_1Boosting.html',1,'LightGBM']]],
  ['boundedhistcollection_63',['BoundedHistCollection',['../classxgboost_1_1tree_1_1BoundedHistCollection.html',1,'xgboost::tree']]],
  ['broadcastfunctor_64',['BroadcastFunctor',['../classxgboost_1_1collective_1_1BroadcastFunctor.html',1,'xgboost::collective']]],
  ['bruckmap_65',['BruckMap',['../classLightGBM_1_1BruckMap.html',1,'LightGBM']]],
  ['buildconfiguration_66',['BuildConfiguration',['../classpackager_1_1build__config_1_1BuildConfiguration.html',1,'packager::build_config']]],
  ['builder_67',['Builder',['../classxgboost_1_1tree_1_1ColMaker_1_1Builder.html',1,'xgboost::tree::ColMaker']]],
  ['byte_5fcontainer_5fwith_5fsubtype_68',['byte_container_with_subtype',['../classbyte__container__with__subtype.html',1,'']]]
];
