var searchData=
[
  ['rabitcommunicator_0',['RabitCommunicator',['../classxgboost_1_1collective_1_1RabitCommunicator.html',1,'xgboost::collective']]],
  ['rabitcontext_1',['RabitContext',['../classxgboost_1_1rabit_1_1RabitContext.html',1,'xgboost::rabit']]],
  ['rabittracker_2',['rabittracker',['../classml_1_1dmlc_1_1xgboost4j_1_1java_1_1RabitTracker.html',1,'ml.dmlc.xgboost4j.java.RabitTracker'],['../classdmlc__tracker_1_1tracker_1_1RabitTracker.html',1,'dmlc_tracker.tracker.RabitTracker'],['../classxgboost_1_1tracker_1_1RabitTracker.html',1,'xgboost.tracker.RabitTracker']]],
  ['random_3',['Random',['../classLightGBM_1_1Random.html',1,'LightGBM']]],
  ['randomdatagenerator_4',['RandomDataGenerator',['../classxgboost_1_1RandomDataGenerator.html',1,'xgboost']]],
  ['randomfeatureselector_5',['RandomFeatureSelector',['../classxgboost_1_1linear_1_1RandomFeatureSelector.html',1,'xgboost::linear']]],
  ['randomreplace_6',['RandomReplace',['../structxgboost_1_1tree_1_1RandomReplace.html',1,'xgboost::tree']]],
  ['randomsamplesgenerator_7',['RandomSamplesGenerator',['../classRandomSamplesGenerator.html',1,'']]],
  ['randomthreadlocalentry_8',['RandomThreadLocalEntry',['../structxgboost_1_1common_1_1RandomThreadLocalEntry.html',1,'xgboost::common']]],
  ['range_9',['Range',['../classxgboost_1_1common_1_1Range.html',1,'xgboost::common']]],
  ['range1d_10',['Range1d',['../classxgboost_1_1common_1_1Range1d.html',1,'xgboost::common']]],
  ['rangecalculator_11',['RangeCalculator',['../classRangeCalculator.html',1,'']]],
  ['rangefeatgenerator_12',['RangeFeatGenerator',['../classRangeFeatGenerator.html',1,'']]],
  ['rangestatus_13',['RangeStatus',['../structRangeStatus.html',1,'']]],
  ['rangetag_14',['RangeTag',['../structxgboost_1_1linalg_1_1detail_1_1RangeTag.html',1,'xgboost::linalg::detail']]],
  ['rankingcache_15',['RankingCache',['../classxgboost_1_1ltr_1_1RankingCache.html',1,'xgboost::ltr']]],
  ['ratiocalculator_16',['RatioCalculator',['../classRatioCalculator.html',1,'']]],
  ['rbitspolicy_17',['RBitsPolicy',['../structxgboost_1_1RBitsPolicy.html',1,'xgboost']]],
  ['readstream_18',['ReadStream',['../classdmlc_1_1io_1_1s3_1_1ReadStream.html',1,'dmlc::io::s3']]],
  ['readstringstream_19',['ReadStringStream',['../structdmlc_1_1io_1_1s3_1_1ReadStringStream.html',1,'dmlc::io::s3']]],
  ['readwrapper_20',['ReadWrapper',['../structrabit_1_1c__api_1_1ReadWrapper.html',1,'rabit::c_api']]],
  ['reallocvector_21',['ReallocVector',['../classxgboost_1_1common_1_1ReallocVector.html',1,'xgboost::common']]],
  ['rebind_22',['rebind',['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; T &gt;::rebind&lt; U &gt;'],['../structxgboost_1_1common_1_1cuda_1_1pinned__allocator_3_01void_01_4_1_1rebind.html',1,'xgboost::common::cuda::pinned_allocator&lt; void &gt;::rebind']]],
  ['recordbatchesiteradapter_23',['RecordBatchesIterAdapter',['../classxgboost_1_1data_1_1RecordBatchesIterAdapter.html',1,'xgboost::data']]],
  ['recorddata_24',['RecordData',['../classRecordData.html',1,'']]],
  ['recordiochunkreader_25',['RecordIOChunkReader',['../classdmlc_1_1RecordIOChunkReader.html',1,'dmlc']]],
  ['recordioreader_26',['RecordIOReader',['../classdmlc_1_1RecordIOReader.html',1,'dmlc']]],
  ['recordiosplitter_27',['RecordIOSplitter',['../classdmlc_1_1io_1_1RecordIOSplitter.html',1,'dmlc::io']]],
  ['recordiowriter_28',['RecordIOWriter',['../classdmlc_1_1RecordIOWriter.html',1,'dmlc']]],
  ['recursivehalvingmap_29',['RecursiveHalvingMap',['../classLightGBM_1_1RecursiveHalvingMap.html',1,'LightGBM']]],
  ['reflinkvector_30',['RefLinkVector',['../structrabit_1_1engine_1_1AllreduceBase_1_1RefLinkVector.html',1,'rabit::engine::AllreduceBase']]],
  ['refresourceview_31',['RefResourceView',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20columntype_20_3e_32',['RefResourceView&lt; ColumnType &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3asize_5ft_20_3e_33',['RefResourceView&lt; std::size_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['refresourceview_3c_20std_3a_3auint8_5ft_20_3e_34',['RefResourceView&lt; std::uint8_t &gt;',['../classxgboost_1_1common_1_1RefResourceView.html',1,'xgboost::common']]],
  ['registry_35',['Registry',['../classdmlc_1_1Registry.html',1,'dmlc']]],
  ['registrydecisionranges_36',['RegistryDecisionRanges',['../classRegistryDecisionRanges.html',1,'']]],
  ['registryevent_37',['RegistryEvent',['../classRegistryEvent.html',1,'']]],
  ['registrysignal_38',['RegistrySignal',['../classRegistrySignal.html',1,'']]],
  ['registrysignaland_39',['RegistrySignalAnd',['../classRegistrySignalAnd.html',1,'']]],
  ['registrysignalany_40',['RegistrySignalAny',['../classRegistrySignalAny.html',1,'']]],
  ['registrysignaldrug_41',['RegistrySignalDrug',['../classRegistrySignalDrug.html',1,'']]],
  ['registrysignalrange_42',['RegistrySignalRange',['../classRegistrySignalRange.html',1,'']]],
  ['registrysignalset_43',['RegistrySignalSet',['../classRegistrySignalSet.html',1,'']]],
  ['reglossobjoneapi_44',['RegLossObjOneAPI',['../classxgboost_1_1obj_1_1RegLossObjOneAPI.html',1,'xgboost::obj']]],
  ['reglossparamoneapi_45',['RegLossParamOneAPI',['../structxgboost_1_1obj_1_1RegLossParamOneAPI.html',1,'xgboost::obj']]],
  ['regression_5fparams_46',['Regression_Params',['../classRegression__Params.html',1,'']]],
  ['regressionfairloss_47',['RegressionFairLoss',['../classLightGBM_1_1RegressionFairLoss.html',1,'LightGBM']]],
  ['regressiongammaloss_48',['RegressionGammaLoss',['../classLightGBM_1_1RegressionGammaLoss.html',1,'LightGBM']]],
  ['regressionhuberloss_49',['RegressionHuberLoss',['../classLightGBM_1_1RegressionHuberLoss.html',1,'LightGBM']]],
  ['regressionl1loss_50',['RegressionL1loss',['../classLightGBM_1_1RegressionL1loss.html',1,'LightGBM']]],
  ['regressionl2loss_51',['RegressionL2loss',['../classLightGBM_1_1RegressionL2loss.html',1,'LightGBM']]],
  ['regressionmapeloss_52',['RegressionMAPELOSS',['../classLightGBM_1_1RegressionMAPELOSS.html',1,'LightGBM']]],
  ['regressionmetric_53',['RegressionMetric',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20fairlossmetric_20_3e_54',['RegressionMetric&lt; FairLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammadeviancemetric_20_3e_55',['RegressionMetric&lt; GammaDevianceMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20gammametric_20_3e_56',['RegressionMetric&lt; GammaMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20huberlossmetric_20_3e_57',['RegressionMetric&lt; HuberLossMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l1metric_20_3e_58',['RegressionMetric&lt; L1Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20l2metric_20_3e_59',['RegressionMetric&lt; L2Metric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20mapemetric_20_3e_60',['RegressionMetric&lt; MAPEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20poissonmetric_20_3e_61',['RegressionMetric&lt; PoissonMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20quantilemetric_20_3e_62',['RegressionMetric&lt; QuantileMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20rmsemetric_20_3e_63',['RegressionMetric&lt; RMSEMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionmetric_3c_20tweediemetric_20_3e_64',['RegressionMetric&lt; TweedieMetric &gt;',['../classLightGBM_1_1RegressionMetric.html',1,'LightGBM']]],
  ['regressionpoissonloss_65',['RegressionPoissonLoss',['../classLightGBM_1_1RegressionPoissonLoss.html',1,'LightGBM']]],
  ['regressionquantileloss_66',['RegressionQuantileloss',['../classLightGBM_1_1RegressionQuantileloss.html',1,'LightGBM']]],
  ['regressiontweedieloss_67',['RegressionTweedieLoss',['../classLightGBM_1_1RegressionTweedieLoss.html',1,'LightGBM']]],
  ['regtree_68',['RegTree',['../classxgboost_1_1RegTree.html',1,'xgboost']]],
  ['reldatacv_69',['RelDataCV',['../classxgboost_1_1testing_1_1data_1_1RelDataCV.html',1,'xgboost::testing::data']]],
  ['remove_5fstats_70',['remove_stats',['../classremove__stats.html',1,'']]],
  ['repaggregatesignal_71',['RepAggregateSignal',['../classRepAggregateSignal.html',1,'']]],
  ['repaggregationperiod_72',['RepAggregationPeriod',['../classRepAggregationPeriod.html',1,'']]],
  ['repbasicoutliercleaner_73',['RepBasicOutlierCleaner',['../classRepBasicOutlierCleaner.html',1,'']]],
  ['repbasicrangecleaner_74',['RepBasicRangeCleaner',['../classRepBasicRangeCleaner.html',1,'']]],
  ['repcalcsimplesignals_75',['RepCalcSimpleSignals',['../classRepCalcSimpleSignals.html',1,'']]],
  ['repcategorydescenders_76',['RepCategoryDescenders',['../classRepCategoryDescenders.html',1,'']]],
  ['repcheckreq_77',['RepCheckReq',['../classRepCheckReq.html',1,'']]],
  ['repclearsignalbydiag_78',['RepClearSignalByDiag',['../classRepClearSignalByDiag.html',1,'']]],
  ['repcombinesignals_79',['RepCombineSignals',['../classRepCombineSignals.html',1,'']]],
  ['repconfiguredoutliercleaner_80',['RepConfiguredOutlierCleaner',['../classRepConfiguredOutlierCleaner.html',1,'']]],
  ['repcreatebitsignal_81',['RepCreateBitSignal',['../classRepCreateBitSignal.html',1,'']]],
  ['repcreateregistry_82',['RepCreateRegistry',['../classRepCreateRegistry.html',1,'']]],
  ['repfilterbychannel_83',['RepFilterByChannel',['../classRepFilterByChannel.html',1,'']]],
  ['rephistorylimit_84',['RepHistoryLimit',['../classRepHistoryLimit.html',1,'']]],
  ['repmultiprocessor_85',['RepMultiProcessor',['../classRepMultiProcessor.html',1,'']]],
  ['repnbrsoutliercleaner_86',['RepNbrsOutlierCleaner',['../classRepNbrsOutlierCleaner.html',1,'']]],
  ['repnumericnoiser_87',['RepNumericNoiser',['../classRepNumericNoiser.html',1,'']]],
  ['repositoryhandle_88',['RepositoryHandle',['../classRepositoryHandle.html',1,'']]],
  ['reppanelcompleter_89',['RepPanelCompleter',['../classRepPanelCompleter.html',1,'']]],
  ['repprocessor_90',['RepProcessor',['../classRepProcessor.html',1,'']]],
  ['repreoderchannels_91',['RepReoderChannels',['../classRepReoderChannels.html',1,'']]],
  ['reprulebasedoutliercleaner_92',['RepRuleBasedOutlierCleaner',['../classRepRuleBasedOutlierCleaner.html',1,'']]],
  ['repsignalrate_93',['RepSignalRate',['../classRepSignalRate.html',1,'']]],
  ['repsimvalhandler_94',['RepSimValHandler',['../classRepSimValHandler.html',1,'']]],
  ['repsplitsignal_95',['RepSplitSignal',['../classRepSplitSignal.html',1,'']]],
  ['requiredsignalfilter_96',['RequiredSignalFilter',['../classRequiredSignalFilter.html',1,'']]],
  ['resamplemissingprocessor_97',['ResampleMissingProcessor',['../classResampleMissingProcessor.html',1,'']]],
  ['resourcehandler_98',['ResourceHandler',['../classxgboost_1_1common_1_1ResourceHandler.html',1,'xgboost::common']]],
  ['returntype_99',['ReturnType',['../structrabit_1_1engine_1_1AllreduceBase_1_1ReturnType.html',1,'rabit::engine::AllreduceBase']]],
  ['rf_100',['RF',['../classLightGBM_1_1RF.html',1,'LightGBM']]],
  ['rmmallocator_101',['RMMAllocator',['../classxgboost_1_1RMMAllocator.html',1,'xgboost']]],
  ['rmsemetric_102',['RMSEMetric',['../classLightGBM_1_1RMSEMetric.html',1,'LightGBM']]],
  ['roc_5fand_5ffilter_5fparams_103',['ROC_And_Filter_Params',['../structROC__And__Filter__Params.html',1,'']]],
  ['roc_5fparams_104',['ROC_Params',['../classROC__Params.html',1,'']]],
  ['row_105',['Row',['../classdmlc_1_1Row.html',1,'dmlc']]],
  ['rowblock_106',['RowBlock',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20indextype_2c_20real_5ft_20_3e_107',['RowBlock&lt; IndexType, real_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_20_3e_108',['RowBlock&lt; uint32_t &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblock_3c_20uint32_5ft_2c_20float_20_3e_109',['RowBlock&lt; uint32_t, float &gt;',['../structdmlc_1_1RowBlock.html',1,'dmlc']]],
  ['rowblockcontainer_110',['RowBlockContainer',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockcontainer_3c_20indextype_2c_20real_5ft_20_3e_111',['RowBlockContainer&lt; IndexType, real_t &gt;',['../structdmlc_1_1data_1_1RowBlockContainer.html',1,'dmlc::data']]],
  ['rowblockiter_112',['RowBlockIter',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowblockiter_3c_20indextype_2c_20real_5ft_20_3e_113',['RowBlockIter&lt; IndexType, real_t &gt;',['../classdmlc_1_1RowBlockIter.html',1,'dmlc']]],
  ['rowsetcollection_114',['RowSetCollection',['../classxgboost_1_1common_1_1RowSetCollection.html',1,'xgboost::common']]],
  ['rtreenodestat_115',['RTreeNodeStat',['../structxgboost_1_1RTreeNodeStat.html',1,'xgboost']]],
  ['runtimeflags_116',['RuntimeFlags',['../structxgboost_1_1common_1_1RuntimeFlags.html',1,'xgboost::common']]],
  ['ryupowlogutils_117',['RyuPowLogUtils',['../structxgboost_1_1detail_1_1RyuPowLogUtils.html',1,'xgboost::detail']]],
  ['ryuprinter_118',['RyuPrinter',['../classxgboost_1_1detail_1_1RyuPrinter.html',1,'xgboost::detail']]]
];
