var searchData=
[
  ['s3filesystem_0',['S3FileSystem',['../classdmlc_1_1io_1_1S3FileSystem.html',1,'dmlc::io']]],
  ['samplefilter_1',['SampleFilter',['../classSampleFilter.html',1,'']]],
  ['samplesbucket_2',['SamplesBucket',['../structSamplesBucket.html',1,'']]],
  ['samplesgenerator_3',['SamplesGenerator',['../classSamplesGenerator.html',1,'']]],
  ['sampling_5fcandidate_4',['sampling_candidate',['../structsampling__candidate.html',1,'']]],
  ['samplingparams_5',['SamplingParams',['../structSamplingParams.html',1,'']]],
  ['samplingres_6',['SamplingRes',['../classSamplingRes.html',1,'']]],
  ['sanitysimplefilter_7',['SanitySimpleFilter',['../classSanitySimpleFilter.html',1,'']]],
  ['sched_8',['Sched',['../structxgboost_1_1common_1_1Sched.html',1,'xgboost::common']]],
  ['scompactdateval_9',['SCompactDateVal',['../classSCompactDateVal.html',1,'']]],
  ['scoreupdater_10',['ScoreUpdater',['../classLightGBM_1_1ScoreUpdater.html',1,'LightGBM']]],
  ['sdatefloat2_11',['SDateFloat2',['../classSDateFloat2.html',1,'']]],
  ['sdaterangeval_12',['SDateRangeVal',['../classSDateRangeVal.html',1,'']]],
  ['sdaterangeval2_13',['SDateRangeVal2',['../classSDateRangeVal2.html',1,'']]],
  ['sdateshort2_14',['SDateShort2',['../classSDateShort2.html',1,'']]],
  ['sdateval_15',['SDateVal',['../classSDateVal.html',1,'']]],
  ['sdateval2_16',['SDateVal2',['../classSDateVal2.html',1,'']]],
  ['secondparam_17',['SecondParam',['../structSecondParam.html',1,'']]],
  ['seekstream_18',['SeekStream',['../classdmlc_1_1SeekStream.html',1,'dmlc']]],
  ['segment_19',['Segment',['../structxgboost_1_1RegTree_1_1CategoricalSplitMatrix_1_1Segment.html',1,'xgboost::RegTree::CategoricalSplitMatrix']]],
  ['sepfilereader_20',['SepFileReader',['../classSepFileReader.html',1,'']]],
  ['sepfilereader_3c_20string_20_3e_21',['SepFileReader&lt; string &gt;',['../classSepFileReader_3_01string_01_4.html',1,'']]],
  ['serializable_22',['Serializable',['../classdmlc_1_1Serializable.html',1,'dmlc']]],
  ['serializableobject_23',['SerializableObject',['../classSerializableObject.html',1,'']]],
  ['serializationtest_24',['SerializationTest',['../classxgboost_1_1SerializationTest.html',1,'xgboost']]],
  ['serializer_25',['serializer',['../classdetail_1_1serializer.html',1,'detail']]],
  ['serialtreelearner_26',['SerialTreeLearner',['../classLightGBM_1_1SerialTreeLearner.html',1,'LightGBM']]],
  ['series_27',['Series',['../classlightgbm_1_1compat_1_1Series.html',1,'lightgbm::compat']]],
  ['serverfortest_28',['ServerForTest',['../classxgboost_1_1ServerForTest.html',1,'xgboost']]],
  ['setcalculator_29',['SetCalculator',['../classSetCalculator.html',1,'']]],
  ['sexprec_5falign_30',['SEXPREC_ALIGN',['../unionSEXPREC__ALIGN.html',1,'']]],
  ['sgd_31',['SGD',['../classSGD.html',1,'']]],
  ['shapleyexplainer_32',['ShapleyExplainer',['../classShapleyExplainer.html',1,'']]],
  ['shotgunupdater_33',['ShotgunUpdater',['../classxgboost_1_1linear_1_1ShotgunUpdater.html',1,'xgboost::linear']]],
  ['shufflefeatureselector_34',['ShuffleFeatureSelector',['../classxgboost_1_1linear_1_1ShuffleFeatureSelector.html',1,'xgboost::linear']]],
  ['sig_5finfo_35',['sig_info',['../structsig__info.html',1,'']]],
  ['signaldatahandle_36',['SignalDataHandle',['../classSignalDataHandle.html',1,'']]],
  ['signalinfo_37',['SignalInfo',['../classSignalInfo.html',1,'']]],
  ['signalparams_38',['SignalParams',['../classSignalParams.html',1,'']]],
  ['simplebatchiteratorimpl_39',['SimpleBatchIteratorImpl',['../classxgboost_1_1data_1_1SimpleBatchIteratorImpl.html',1,'xgboost::data']]],
  ['simplecalculator_40',['SimpleCalculator',['../classSimpleCalculator.html',1,'']]],
  ['simpledmatrix_41',['SimpleDMatrix',['../classxgboost_1_1data_1_1SimpleDMatrix.html',1,'xgboost::data']]],
  ['simpleexampleegfralgomarker_42',['SimpleExampleEGFRAlgoMarker',['../classSimpleExampleEGFRAlgoMarker.html',1,'']]],
  ['simplelcg_43',['SimpleLCG',['../classxgboost_1_1SimpleLCG.html',1,'xgboost']]],
  ['simplerealuniformdistribution_44',['SimpleRealUniformDistribution',['../classxgboost_1_1SimpleRealUniformDistribution.html',1,'xgboost']]],
  ['singlebatchdataiter_45',['SingleBatchDataIter',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20arrayadapterbatch_20_3e_46',['SingleBatchDataIter&lt; ArrayAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20cscadapterbatch_20_3e_47',['SingleBatchDataIter&lt; CSCAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20cscarrayadapterbatch_20_3e_48',['SingleBatchDataIter&lt; CSCArrayAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20csradapterbatch_20_3e_49',['SingleBatchDataIter&lt; CSRAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20csrarrayadapterbatch_20_3e_50',['SingleBatchDataIter&lt; CSRArrayAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20datatableadapterbatch_20_3e_51',['SingleBatchDataIter&lt; DataTableAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchdataiter_3c_20denseadapterbatch_20_3e_52',['SingleBatchDataIter&lt; DenseAdapterBatch &gt;',['../classxgboost_1_1data_1_1detail_1_1SingleBatchDataIter.html',1,'xgboost::data::detail']]],
  ['singlebatchinternaliter_53',['SingleBatchInternalIter',['../classxgboost_1_1data_1_1SingleBatchInternalIter.html',1,'xgboost::data']]],
  ['singledataelement_54',['SingleDataElement',['../classAlgoMarker_1_1AlgoMarker_1_1SingleDataElement.html',1,'AlgoMarker::AlgoMarker']]],
  ['singlefilesplit_55',['SingleFileSplit',['../classdmlc_1_1io_1_1SingleFileSplit.html',1,'dmlc::io']]],
  ['singlethreadedinputsplit_56',['SingleThreadedInputSplit',['../classdmlc_1_1io_1_1SingleThreadedInputSplit.html',1,'dmlc::io']]],
  ['singletongenerator_57',['SingletonGenerator',['../classSingletonGenerator.html',1,'']]],
  ['sketchcontainerimpl_58',['SketchContainerImpl',['../classxgboost_1_1common_1_1SketchContainerImpl.html',1,'xgboost::common']]],
  ['sketchcontainerimpl_3c_20wquantilesketch_3c_20float_2c_20float_20_3e_20_3e_59',['SketchContainerImpl&lt; WQuantileSketch&lt; float, float &gt; &gt;',['../classxgboost_1_1common_1_1SketchContainerImpl.html',1,'xgboost::common']]],
  ['sketchcontainerimpl_3c_20wxquantilesketch_3c_20float_2c_20float_20_3e_20_3e_60',['SketchContainerImpl&lt; WXQuantileSketch&lt; float, float &gt; &gt;',['../classxgboost_1_1common_1_1SketchContainerImpl.html',1,'xgboost::common']]],
  ['slaveentry_61',['SlaveEntry',['../classdmlc__tracker_1_1tracker_1_1SlaveEntry.html',1,'dmlc_tracker::tracker']]],
  ['smokinggenerator_62',['SmokingGenerator',['../classSmokingGenerator.html',1,'']]],
  ['sockaddress_63',['SockAddress',['../classxgboost_1_1collective_1_1SockAddress.html',1,'xgboost::collective']]],
  ['sockaddrv4_64',['SockAddrV4',['../classxgboost_1_1collective_1_1SockAddrV4.html',1,'xgboost::collective']]],
  ['sockaddrv6_65',['SockAddrV6',['../classxgboost_1_1collective_1_1SockAddrV6.html',1,'xgboost::collective']]],
  ['solutioninfo_66',['SolutionInfo',['../structSolver_1_1SolutionInfo.html',1,'Solver']]],
  ['solver_67',['Solver',['../classSolver.html',1,'']]],
  ['solver_5fnu_68',['Solver_NU',['../classSolver__NU.html',1,'']]],
  ['sort_5fspecial_69',['sort_special',['../structsort__special.html',1,'']]],
  ['sortedcscpage_70',['SortedCSCPage',['../classxgboost_1_1SortedCSCPage.html',1,'xgboost']]],
  ['sortedcscpagesource_71',['SortedCSCPageSource',['../classxgboost_1_1data_1_1SortedCSCPageSource.html',1,'xgboost::data']]],
  ['sortedquantile_72',['SortedQuantile',['../structxgboost_1_1common_1_1SortedQuantile.html',1,'xgboost::common']]],
  ['sortedsketchcontainer_73',['SortedSketchContainer',['../classxgboost_1_1common_1_1SortedSketchContainer.html',1,'xgboost::common']]],
  ['sourcelocation_74',['SourceLocation',['../structxgboost_1_1JsonReader_1_1SourceLocation.html',1,'xgboost::JsonReader']]],
  ['span_75',['Span',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20bst_5frow_5ft_20const_20_3e_76',['Span&lt; bst_row_t const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20const_20binidxt_20_3e_77',['Span&lt; const BinIdxT &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20const_20binidxtype_20_3e_78',['Span&lt; const BinIdxType &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20const_20size_5ft_20_3e_79',['Span&lt; const size_t &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20featuretype_20const_20_3e_80',['Span&lt; FeatureType const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20float_20const_20_3e_81',['Span&lt; float const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20std_3a_3auint8_5ft_20_3e_82',['Span&lt; std::uint8_t &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20uint32_5ft_20const_20_3e_83',['Span&lt; uint32_t const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20xgboost_3a_3aentry_20const_20_3e_84',['Span&lt; xgboost::Entry const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['span_3c_20xgboost_3a_3aregtree_3a_3acategoricalsplitmatrix_3a_3asegment_20const_20_3e_85',['Span&lt; xgboost::RegTree::CategoricalSplitMatrix::Segment const &gt;',['../classxgboost_1_1common_1_1Span.html',1,'xgboost::common']]],
  ['spaniterator_86',['SpanIterator',['../classxgboost_1_1common_1_1detail_1_1SpanIterator.html',1,'xgboost::common::detail']]],
  ['sparklocalclustertestcase_87',['SparkLocalClusterTestCase',['../classtest__distributed_1_1test__with__spark_1_1utils_1_1SparkLocalClusterTestCase.html',1,'test_distributed::test_with_spark::utils']]],
  ['sparktestcase_88',['SparkTestCase',['../classtest__distributed_1_1test__with__spark_1_1utils_1_1SparkTestCase.html',1,'test_distributed::test_with_spark::utils']]],
  ['sparkxgbclassifier_89',['SparkXGBClassifier',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBClassifier.html',1,'xgboost::spark::estimator']]],
  ['sparkxgbclassifiermodel_90',['SparkXGBClassifierModel',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBClassifierModel.html',1,'xgboost::spark::estimator']]],
  ['sparkxgbranker_91',['SparkXGBRanker',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBRanker.html',1,'xgboost::spark::estimator']]],
  ['sparkxgbrankermodel_92',['SparkXGBRankerModel',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBRankerModel.html',1,'xgboost::spark::estimator']]],
  ['sparkxgbregressor_93',['SparkXGBRegressor',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBRegressor.html',1,'xgboost::spark::estimator']]],
  ['sparkxgbregressormodel_94',['SparkXGBRegressorModel',['../classxgboost_1_1spark_1_1estimator_1_1SparkXGBRegressorModel.html',1,'xgboost::spark::estimator']]],
  ['sparsebin_95',['SparseBin',['../classLightGBM_1_1SparseBin.html',1,'LightGBM']]],
  ['sparsebiniterator_96',['SparseBinIterator',['../classLightGBM_1_1SparseBinIterator.html',1,'LightGBM']]],
  ['sparsecolumniter_97',['SparseColumnIter',['../classxgboost_1_1common_1_1SparseColumnIter.html',1,'xgboost::common']]],
  ['sparsematrowmetadata_98',['SparseMatRowMetaData',['../structSparseMatRowMetaData.html',1,'']]],
  ['sparsepage_99',['SparsePage',['../classxgboost_1_1SparsePage.html',1,'xgboost']]],
  ['sparsepageadapterbatch_100',['SparsePageAdapterBatch',['../classxgboost_1_1data_1_1SparsePageAdapterBatch.html',1,'xgboost::data']]],
  ['sparsepagedmatrix_101',['SparsePageDMatrix',['../classxgboost_1_1data_1_1SparsePageDMatrix.html',1,'xgboost::data']]],
  ['sparsepageformat_102',['SparsePageFormat',['../classxgboost_1_1data_1_1SparsePageFormat.html',1,'xgboost::data']]],
  ['sparsepageformat_3c_20ghistindexmatrix_20_3e_103',['SparsePageFormat&lt; GHistIndexMatrix &gt;',['../classxgboost_1_1data_1_1SparsePageFormat.html',1,'xgboost::data']]],
  ['sparsepageformatreg_104',['SparsePageFormatReg',['../structxgboost_1_1data_1_1SparsePageFormatReg.html',1,'xgboost::data']]],
  ['sparsepagerawformat_105',['SparsePageRawFormat',['../classxgboost_1_1data_1_1SparsePageRawFormat.html',1,'xgboost::data']]],
  ['sparsepagesource_106',['SparsePageSource',['../classxgboost_1_1data_1_1SparsePageSource.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_107',['SparsePageSourceImpl',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_3c_20cscpage_20_3e_108',['SparsePageSourceImpl&lt; CSCPage &gt;',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_3c_20ellpackpage_20_3e_109',['SparsePageSourceImpl&lt; EllpackPage &gt;',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_3c_20ghistindexmatrix_20_3e_110',['SparsePageSourceImpl&lt; GHistIndexMatrix &gt;',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_3c_20sortedcscpage_20_3e_111',['SparsePageSourceImpl&lt; SortedCSCPage &gt;',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepagesourceimpl_3c_20sparsepage_20_3e_112',['SparsePageSourceImpl&lt; SparsePage &gt;',['../classxgboost_1_1data_1_1SparsePageSourceImpl.html',1,'xgboost::data']]],
  ['sparsepair_113',['SparsePair',['../structLightGBM_1_1OrderedSparseBin_1_1SparsePair.html',1,'LightGBM::OrderedSparseBin']]],
  ['splitentrycontainer_114',['SplitEntryContainer',['../structxgboost_1_1tree_1_1SplitEntryContainer.html',1,'xgboost::tree']]],
  ['splitentrycontainer_3c_20gradstats_20_3e_115',['SplitEntryContainer&lt; GradStats &gt;',['../structxgboost_1_1tree_1_1SplitEntryContainer.html',1,'xgboost::tree']]],
  ['splitentrycontainer_3c_20std_3a_3avector_3c_20xgboost_3a_3adetail_3a_3agradientpairinternal_20_3e_20_3e_116',['SplitEntryContainer&lt; std::vector&lt; xgboost::detail::GradientPairInternal &gt; &gt;',['../structxgboost_1_1tree_1_1SplitEntryContainer.html',1,'xgboost::tree']]],
  ['splitevaluator_117',['SplitEvaluator',['../structxgboost_1_1tree_1_1TreeEvaluator_1_1SplitEvaluator.html',1,'xgboost::tree::TreeEvaluator']]],
  ['splitinfo_118',['SplitInfo',['../structLightGBM_1_1SplitInfo.html',1,'LightGBM']]],
  ['splittype_119',['SplitType',['../classjson__parser_1_1SplitType.html',1,'json_parser']]],
  ['squaredlogerror_120',['SquaredLogError',['../structxgboost_1_1obj_1_1SquaredLogError.html',1,'xgboost::obj']]],
  ['squaredlogerroroneapi_121',['SquaredLogErrorOneAPI',['../structxgboost_1_1obj_1_1SquaredLogErrorOneAPI.html',1,'xgboost::obj']]],
  ['static_5fconst_122',['static_const',['../structdetail_1_1static__const.html',1,'detail']]],
  ['statics_123',['Statics',['../structjson11_1_1Statics.html',1,'json11']]],
  ['stimelongval_124',['STimeLongVal',['../classSTimeLongVal.html',1,'']]],
  ['stimerange_125',['STimeRange',['../classSTimeRange.html',1,'']]],
  ['stimerangeval_126',['STimeRangeVal',['../classSTimeRangeVal.html',1,'']]],
  ['stimeshort4_127',['STimeShort4',['../classSTimeShort4.html',1,'']]],
  ['stimestamp_128',['STimeStamp',['../classSTimeStamp.html',1,'']]],
  ['stimeval_129',['STimeVal',['../classSTimeVal.html',1,'']]],
  ['stopiterator_130',['StopIterator',['../classStopIterator.html',1,'']]],
  ['str2t_131',['Str2T',['../classdmlc_1_1Str2T.html',1,'dmlc']]],
  ['str2t_3c_20double_20_3e_132',['Str2T&lt; double &gt;',['../classdmlc_1_1Str2T_3_01double_01_4.html',1,'dmlc']]],
  ['str2t_3c_20float_20_3e_133',['Str2T&lt; float &gt;',['../classdmlc_1_1Str2T_3_01float_01_4.html',1,'dmlc']]],
  ['str2t_3c_20int32_5ft_20_3e_134',['Str2T&lt; int32_t &gt;',['../classdmlc_1_1Str2T_3_01int32__t_01_4.html',1,'dmlc']]],
  ['str2t_3c_20int64_5ft_20_3e_135',['Str2T&lt; int64_t &gt;',['../classdmlc_1_1Str2T_3_01int64__t_01_4.html',1,'dmlc']]],
  ['str2t_3c_20uint32_5ft_20_3e_136',['Str2T&lt; uint32_t &gt;',['../classdmlc_1_1Str2T_3_01uint32__t_01_4.html',1,'dmlc']]],
  ['str2t_3c_20uint64_5ft_20_3e_137',['Str2T&lt; uint64_t &gt;',['../classdmlc_1_1Str2T_3_01uint64__t_01_4.html',1,'dmlc']]],
  ['stream_138',['Stream',['../classdmlc_1_1Stream.html',1,'dmlc']]],
  ['streambufferreader_139',['StreamBufferReader',['../classxgboost_1_1common_1_1StreamBufferReader.html',1,'xgboost::common']]],
  ['stringview_140',['StringView',['../structxgboost_1_1StringView.html',1,'xgboost']]],
  ['sum_141',['Sum',['../structrabit_1_1op_1_1Sum.html',1,'rabit::op']]],
  ['sumcalculator_142',['SumCalculator',['../classSumCalculator.html',1,'']]],
  ['summarycontainer_143',['SummaryContainer',['../structxgboost_1_1common_1_1QuantileSketchTemplate_1_1SummaryContainer.html',1,'xgboost::common::QuantileSketchTemplate']]],
  ['supportedtasks_144',['SupportedTasks',['../classtrainer_1_1SupportedTasks.html',1,'trainer']]],
  ['sval_145',['SVal',['../classSVal.html',1,'']]],
  ['svalshort2_146',['SValShort2',['../classSValShort2.html',1,'']]],
  ['svalshort4_147',['SValShort4',['../classSValShort4.html',1,'']]],
  ['svc_5fq_148',['SVC_Q',['../classSVC__Q.html',1,'']]],
  ['svm_5fmodel_149',['svm_model',['../structsvm__model.html',1,'']]],
  ['svm_5fnode_150',['svm_node',['../structsvm__node.html',1,'']]],
  ['svm_5fparameter_151',['svm_parameter',['../structsvm__parameter.html',1,'']]],
  ['svm_5fproblem_152',['svm_problem',['../structsvm__problem.html',1,'']]],
  ['svr_5fq_153',['SVR_Q',['../classSVR__Q.html',1,'']]]
];
