var searchData=
[
  ['lambdarank_20example_0',['LambdaRank Example',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2examples_2lambdarank_2README.html',1,'']]],
  ['learning_1',['learning',['../md_External_2xgboost_2dmlc-core_2doc_2parameter.html',1,'Parameter Structure for Machine Learning'],['../md_External_2xgboost_2plugin_2federated_2README.html',1,'XGBoost Plugin for Federated Learning']]],
  ['learning_20common_20codebase_2',['Distributed Machine Learning Common Codebase',['../md_External_2xgboost_2dmlc-core_2README.html',1,'']]],
  ['learning_20example_3',['Parallel Learning Example',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2examples_2parallel__learning_2README.html',1,'']]],
  ['learning_20to_20rank_4',['Learning to rank',['../md_External_2xgboost_2demo_2rank_2README.html',1,'']]],
  ['libraries_5',['Medial EarlySign Libraries',['../md_README.html',1,'']]],
  ['libraries_20and_20licenses_6',['Third-Party Libraries and Licenses',['../md_THIRD__PARTY__LICENSES.html',1,'']]],
  ['library_7',['Medial EarlySign Python Library',['../md_Internal_2MedPyExport_2generate__binding_2README.html',1,'']]],
  ['library_20originates_20from_20a_20href_20https_3a_20github_20com_20dmlc_20rabit_20rabit_20a_8',['This directory contains the CPU network module for XGBoost.  The library originates from &lt;a href=&quot;https://github.com/dmlc/rabit&quot; &gt;RABIT&lt;/a&gt;',['../md_External_2xgboost_2rabit_2README.html',1,'']]],
  ['libs_20documentation_9',['Welcome To Medial Libs Documentation',['../index.html',1,'']]],
  ['licenses_10',['Third-Party Libraries and Licenses',['../md_THIRD__PARTY__LICENSES.html',1,'']]],
  ['light_20gradient_20boosting_20machine_11',['LightGBM, Light Gradient Boosting Machine',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2README.html',1,'']]],
  ['lightgbm_12',['Table/List of Key Modifications of LightGBM',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2docs_2Key-Events.html',1,'']]],
  ['lightgbm_20gpu_20version_20with_20python_13',['Dockerfile for LightGBM GPU Version with Python',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2docker_2gpu_2README.html',1,'']]],
  ['lightgbm_20light_20gradient_20boosting_20machine_14',['LightGBM, Light Gradient Boosting Machine',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2README.html',1,'']]],
  ['lightgbm_20r_20package_15',['LightGBM R-package',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2R-package_2README.html',1,'']]],
  ['lightgbm_20via_20docker_16',['Using LightGBM via Docker',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2docker_2README.html',1,'']]],
  ['list_17',['Deprecated List',['../deprecated.html',1,'']]],
  ['list_20of_20key_20modifications_20of_20lightgbm_18',['Table/List of Key Modifications of LightGBM',['../md_External_2LightGBM__2_82_83_2LightGBM-2_82_83_2docs_2Key-Events.html',1,'']]],
  ['load_20data_20from_20external_20memory_19',['Defining a Custom Data Iterator to Load Data from External Memory',['../md_External_2xgboost_2demo_2c-api_2external-memory_2README.html',1,'']]],
  ['log_20',['XGBoost Change Log',['../md_External_2xgboost_2NEWS.html',1,'']]],
  ['logo_20xgboost_20logo_20svg_20width_20135_20extreme_20gradient_20boosting_21',['&lt;img src=&quot;https://xgboost.ai/images/logo/xgboost-logo.svg&quot; width=135/&gt;  eXtreme Gradient Boosting',['../md_External_2xgboost_2README.html',1,'']]]
];
